# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc930250ee2c780441abbb827a7b397ad7d93270a87e7033b94b340a6941d28e0c70e59b48da774ec28433f6459259777c9061cfc16b835b5a6918a9f377cb54

test:
  secret_key_base: 7ac946248a3c92d847a944638840163f326f3c67cedb4b3747f85bd8ee9041cdc18bcf6bfca9cb5170faad48636f05f8160a4c5f03af4944d7d8a28f7691c892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
